type Select = {
  value: string,
  label: string;
}
const genders: Select[] = [
	{
		value: "Male",
		label: "Male"
	},
	{
		value: "Female",
		label: "Female"
	},
	{
		value: "NonBinary",
		label: "Non-Binary"
	},
	{
		value: "None",
		label: "Prefer Not to Say"
	}
];

const pronouns: Select[] = [
	{
		label: "He/Him",
		value: "He/Him"
	},
	{
		label: "She/Her",
		value: "She/Her"
	},
	{
		label: "They/Them",
		value: "They/Them"
	}
];

const countries: Select[] = [
	{ label: "Afghanistan", value: "Afghanistan" },
	{ label: "Albania", value: "Albania" },
	{ label: "Algeria", value: "Algeria" },
	{ label: "Andorra", value: "Andorra" },
	{ label: "Angola", value: "Angola" },
	{ label: "Antigua and Barbuda", value: "Antigua and Barbuda" },
	{ label: "Argentina", value: "Argentina" },
	{ label: "Armenia", value: "Armenia" },
	{ label: "Australia", value: "Australia" },
	{ label: "Austria", value: "Austria" },
	{ label: "Azerbaijan", value: "Azerbaijan" },
	{ label: "Bahamas", value: "Bahamas" },
	{ label: "Bahrain", value: "Bahrain" },
	{ label: "Bangladesh", value: "Bangladesh" },
	{ label: "Barbados", value: "Barbados" },
	{ label: "Belarus", value: "Belarus" },
	{ label: "Belgium", value: "Belgium" },
	{ label: "Belize", value: "Belize" },
	{ label: "Benin", value: "Benin" },
	{ label: "Bhutan", value: "Bhutan" },
	{ label: "Bolivia", value: "Bolivia" },
	{ label: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
	{ label: "Botswana", value: "Botswana" },
	{ label: "Brazil", value: "Brazil" },
	{ label: "Brunei Darussalam", value: "Brunei Darussalam" },
	{ label: "Bulgaria", value: "Bulgaria" },
	{ label: "Burkina Faso", value: "Burkina Faso" },
	{ label: "Burundi", value: "Burundi" },
	{ label: "Cabo Verde", value: "Cabo Verde" },
	{ label: "Cambodia", value: "Cambodia" },
	{ label: "Cameroon", value: "Cameroon" },
	{ label: "Canada", value: "Canada" },
	{ label: "Central African Republic", value: "Central African Republic" },
	{ label: "Chad", value: "Chad" },
	{ label: "Chile", value: "Chile" },
	{ label: "China", value: "China" },
	{ label: "Colombia", value: "Colombia" },
	{ label: "Comoros", value: "Comoros" },
	{ label: "Congo (Republic of the)", value: "Congo (Republic of the)" },
	{ label: "Congo (Democratic Republic of the)", value: "Congo (Democratic Republic of the)" },
	{ label: "Costa Rica", value: "Costa Rica" },
	{ label: "Côte d'Ivoire", value: "Côte d'Ivoire" },
	{ label: "Croatia", value: "Croatia" },
	{ label: "Cuba", value: "Cuba" },
	{ label: "Cyprus", value: "Cyprus" },
	{ label: "Czechia", value: "Czechia" },
	{ label: "Denmark", value: "Denmark" },
	{ label: "Djibouti", value: "Djibouti" },
	{ label: "Dominica", value: "Dominica" },
	{ label: "Dominican Republic", value: "Dominican Republic" },
	{ label: "Ecuador", value: "Ecuador" },
	{ label: "Egypt", value: "Egypt" },
	{ label: "El Salvador", value: "El Salvador" },
	{ label: "Equatorial Guinea", value: "Equatorial Guinea" },
	{ label: "Eritrea", value: "Eritrea" },
	{ label: "Estonia", value: "Estonia" },
	{ label: "Eswatini", value: "Eswatini" },
	{ label: "Ethiopia", value: "Ethiopia" },
	{ label: "Fiji", value: "Fiji" },
	{ label: "Finland", value: "Finland" },
	{ label: "France", value: "France" },
	{ label: "Gabon", value: "Gabon" },
	{ label: "Gambia", value: "Gambia" },
	{ label: "Georgia", value: "Georgia" },
	{ label: "Germany", value: "Germany" },
	{ label: "Ghana", value: "Ghana" },
	{ label: "Greece", value: "Greece" },
	{ label: "Grenada", value: "Grenada" },
	{ label: "Guatemala", value: "Guatemala" },
	{ label: "Guinea", value: "Guinea" },
	{ label: "Guinea-Bissau", value: "Guinea-Bissau" },
	{ label: "Guyana", value: "Guyana" },
	{ label: "Haiti", value: "Haiti" },
	{ label: "Holy See (Vatican City State)", value: "Holy See (Vatican City State)" },
	{ label: "Honduras", value: "Honduras" },
	{ label: "Hungary", value: "Hungary" },
	{ label: "Iceland", value: "Iceland" },
	{ label: "India", value: "India" },
	{ label: "Indonesia", value: "Indonesia" },
	{ label: "Iran", value: "Iran" },
	{ label: "Iraq", value: "Iraq" },
	{ label: "Ireland", value: "Ireland" },
	{ label: "Israel", value: "Israel" },
	{ label: "Italy", value: "Italy" },
	{ label: "Jamaica", value: "Jamaica" },
	{ label: "Japan", value: "Japan" },
	{ label: "Jordan", value: "Jordan" },
	{ label: "Kazakhstan", value: "Kazakhstan" },
	{ label: "Kenya", value: "Kenya" },
	{ label: "Kiribati", value: "Kiribati" },
	{
		label: "Korea (Democratic People's Republic of - North Korea)",
		value: "Korea (Democratic People's Republic of - North Korea)"
	},
	{ label: "Korea (Republic of - South Korea)", value: "Korea (Republic of - South Korea)" },
	{ label: "Kosovo", value: "Kosovo" },
	{ label: "Kuwait", value: "Kuwait" },
	{ label: "Kyrgyzstan", value: "Kyrgyzstan" },
	{ label: "Lao People's Democratic Republic", value: "Lao People's Democratic Republic" },
	{ label: "Latvia", value: "Latvia" },
	{ label: "Lebanon", value: "Lebanon" },
	{ label: "Lesotho", value: "Lesotho" },
	{ label: "Liberia", value: "Liberia" },
	{ label: "Libya", value: "Libya" },
	{ label: "Liechtenstein", value: "Liechtenstein" },
	{ label: "Lithuania", value: "Lithuania" },
	{ label: "Luxembourg", value: "Luxembourg" },
	{ label: "Madagascar", value: "Madagascar" },
	{ label: "Malawi", value: "Malawi" },
	{ label: "Malaysia", value: "Malaysia" },
	{ label: "Maldives", value: "Maldives" },
	{ label: "Mali", value: "Mali" },
	{ label: "Malta", value: "Malta" },
	{ label: "Marshall Islands", value: "Marshall Islands" },
	{ label: "Mauritania", value: "Mauritania" },
	{ label: "Mauritius", value: "Mauritius" },
	{ label: "Mexico", value: "Mexico" },
	{ label: "Micronesia (Federated States of)", value: "Micronesia (Federated States of)" },
	{ label: "Moldova", value: "Moldova" },
	{ label: "Monaco", value: "Monaco" },
	{ label: "Mongolia", value: "Mongolia" },
	{ label: "Montenegro", value: "Montenegro" },
	{ label: "Morocco", value: "Morocco" },
	{ label: "Mozambique", value: "Mozambique" },
	{ label: "Myanmar", value: "Myanmar" },
	{ label: "Namibia", value: "Namibia" },
	{ label: "Nauru", value: "Nauru" },
	{ label: "Nepal", value: "Nepal" },
	{ label: "Netherlands", value: "Netherlands" },
	{ label: "New Zealand", value: "New Zealand" },
	{ label: "Nicaragua", value: "Nicaragua" },
	{ label: "Niger", value: "Niger" },
	{ label: "Nigeria", value: "Nigeria" },
	{ label: "North Macedonia", value: "North Macedonia" },
	{ label: "Norway", value: "Norway" },
	{ label: "Oman", value: "Oman" },
	{ label: "Pakistan", value: "Pakistan" },
	{ label: "Palau", value: "Palau" },
	{
		label: "Palestine (State of - UN observer state)",
		value: "Palestine (State of - UN observer state)"
	},
	{ label: "Panama", value: "Panama" },
	{ label: "Papua New Guinea", value: "Papua New Guinea" },
	{ label: "Paraguay", value: "Paraguay" },
	{ label: "Peru", value: "Peru" },
	{ label: "Philippines", value: "Philippines" },
	{ label: "Poland", value: "Poland" },
	{ label: "Portugal", value: "Portugal" },
	{ label: "Qatar", value: "Qatar" },
	{ label: "Romania", value: "Romania" },
	{ label: "Russian Federation", value: "Russian Federation" },
	{ label: "Rwanda", value: "Rwanda" },
	{ label: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
	{ label: "Saint Lucia", value: "Saint Lucia" },
	{ label: "Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines" },
	{ label: "Samoa", value: "Samoa" },
	{ label: "San Marino", value: "San Marino" },
	{ label: "Sao Tome and Principe", value: "Sao Tome and Principe" },
	{ label: "Saudi Arabia", value: "Saudi Arabia" },
	{ label: "Senegal", value: "Senegal" },
	{ label: "Serbia", value: "Serbia" },
	{ label: "Seychelles", value: "Seychelles" },
	{ label: "Sierra Leone", value: "Sierra Leone" },
	{ label: "Singapore", value: "Singapore" },
	{ label: "Slovakia", value: "Slovakia" },
	{ label: "Slovenia", value: "Slovenia" },
	{ label: "Solomon Islands", value: "Solomon Islands" },
	{ label: "Somalia", value: "Somalia" },
	{ label: "South Africa", value: "South Africa" },
	{ label: "South Sudan", value: "South Sudan" },
	{ label: "Spain", value: "Spain" },
	{ label: "Sri Lanka", value: "Sri Lanka" },
	{ label: "Sudan", value: "Sudan" },
	{ label: "Suriname", value: "Suriname" },
	{ label: "Sweden", value: "Sweden" },
	{ label: "Switzerland", value: "Switzerland" },
	{ label: "Syrian Arab Republic", value: "Syrian Arab Republic" },
	{ label: "Tajikistan", value: "Tajikistan" },
	{ label: "Tanzania (United Republic of)", value: "Tanzania (United Republic of)" },
	{ label: "Thailand", value: "Thailand" },
	{ label: "Timor-Leste", value: "Timor-Leste" },
	{ label: "Togo", value: "Togo" },
	{ label: "Tonga", value: "Tonga" },
	{ label: "Trinidad and Tobago", value: "Trinidad and Tobago" },
	{ label: "Tunisia", value: "Tunisia" },
	{ label: "Turkey", value: "Turkey" },
	{ label: "Turkmenistan", value: "Turkmenistan" },
	{ label: "Tuvalu", value: "Tuvalu" },
	{ label: "Uganda", value: "Uganda" },
	{ label: "Ukraine", value: "Ukraine" },
	{ label: "United Arab Emirates", value: "United Arab Emirates" },
	{ label: "United Kingdom", value: "United Kingdom" },
	{ label: "United States of America", value: "United States of America" },
	{ label: "Uruguay", value: "Uruguay" },
	{ label: "Uzbekistan", value: "Uzbekistan" },
	{ label: "Vanuatu", value: "Vanuatu" },
	{ label: "Venezuela", value: "Venezuela" },
	{ label: "Vietnam", value: "Vietnam" },
	{ label: "Yemen", value: "Yemen" },
	{ label: "Zambia", value: "Zambia" },
	{ label: "Zimbabwe", value: "Zimbabwe" }
];

const dailyAffirmations = [
	// Self-Love & Self-Worth
	"I am enough just as I am.",
	"My worth is not determined by others' opinions.",
	"I deserve love, care, and respect.",
	"I accept myself fully and unconditionally.",
	"My flaws make me unique and human.",
	"I am constantly growing and evolving.",
	"I honor my needs and set healthy boundaries.",
	"I let go of self-judgment and embrace compassion.",
	"I am proud of how far I’ve come.",
	"My presence makes the world better.",

	// Confidence & Empowerment
	"I trust in my ability to overcome challenges.",
	"Confidence flows through me naturally.",
	"I am capable of achieving great things.",
	"I choose to show up fully and authentically.",
	"I am powerful, resilient, and brave.",
	"I release fear and step into courage.",
	"I am worthy of success and happiness.",
	"I learn from setbacks and grow stronger each time.",
	"I deserve to take up space.",
	"My voice matters, and I speak with confidence.",

	// Stress & Anxiety Relief
	"I release what I cannot control.",
	"Peace begins with my breath.",
	"I choose calm over chaos.",
	"I am safe, here and now.",
	"I let go of unnecessary worries.",
	"Each exhale releases tension from my body.",
	"I give myself permission to rest.",
	"I welcome stillness into my day.",
	"I trust that things will work out in time.",
	"My mind is a place of peace and clarity.",

	// Motivation & Productivity
	"Today, I take steps toward my goals.",
	"Small actions create big change over time.",
	"I am focused, capable, and determined.",
	"I use my time wisely and with purpose.",
	"Progress matters more than perfection.",
	"I can handle the tasks ahead of me.",
	"My energy goes toward what truly matters.",
	"I am disciplined and motivated.",
	"Each day is a new chance to move forward.",
	"I finish what I start.",

	// Relationships & Compassion
	"I nurture healthy and supportive connections.",
	"I choose kindness, even in challenging moments.",
	"I am open to love in all its forms.",
	"My relationships are built on mutual respect.",
	"I express my needs with honesty and care.",
	"I am patient with others’ growth, as they are with mine.",
	"I release grudges and choose forgiveness.",
	"I attract people who align with my values.",
	"Love flows easily and abundantly into my life.",
	"I am a source of warmth and understanding.",

	// Healing & Resilience
	"I allow myself to heal at my own pace.",
	"My past does not define my future.",
	"I am stronger than my struggles.",
	"I turn pain into wisdom and growth.",
	"I release what no longer serves me.",
	"Healing is not linear, and that’s okay.",
	"I am gentle with myself as I recover.",
	"I trust the process of renewal.",
	"Every scar tells a story of resilience.",
	"My challenges shape me, not break me.",

	// Gratitude & Positivity
	"I am grateful for this new day.",
	"I find joy in small moments.",
	"My life is full of blessings I choose to notice.",
	"I focus on what’s good and expanding.",
	"I welcome abundance into my life.",
	"Gratitude transforms my perspective.",
	"I appreciate the people who uplift me.",
	"I celebrate the progress I’ve made.",
	"Positivity is a choice I make daily.",
	"I find reasons to smile every day.",

	// Health & Well-Being
	"My body deserves nourishment and care.",
	"I honor my need for rest and movement.",
	"I am grateful for my body’s strength and resilience.",
	"I make choices that support my health.",
	"My mind and body are in balance.",
	"Healing energy flows through me.",
	"I listen to my body’s signals with respect.",
	"I prioritize self-care without guilt.",
	"Each day, I grow stronger and healthier.",
	"I am in tune with my well-being."
];



export const constants = {
  countries, genders, pronouns, dailyAffirmations
}