import type { School, SchoolResource } from "@/lib/types/index";

export const MCMASTER_RESOURCES: Omit<SchoolResource, "id" | "createdAt">[] = [
	{
		name: "Student Wellness Centre",
		url: "https://wellness.mcmaster.ca/",
		type: "Mental Health",
	},
	{
		name: "Good2Talk (24/7 Support)",
		url: "https://good2talk.ca/",
		type: "Crisis Support",
	},
	{
		name: "MSU Food Collective Centre",
		url: "https://msumcmaster.ca/service/food-collective-centre/",
		type: "Food Security",
	},
	{
		name: "Student Success Centre",
		url: "https://studentsuccess.mcmaster.ca/",
		type: "Academic Support",
	},
	{
		name: "Student Accessibility Services",
		url: "https://sas.mcmaster.ca/",
		type: "Accessibility",
	},
];

// Get a list of countries sorted by the user's local language
const getCountryList = (locale = window.navigator.language) => {
	const regionNames = new Intl.DisplayNames([locale], { type: "region" });

	//TODO: add more countries
	const codes = ["CA"];

	return codes
		.map((code) => ({
			code: code,
			name: regionNames.of(code),
		}))
		.sort((a, b) => a.name!.localeCompare(b.name!)); // Alphabetical sort
};

export const countries = getCountryList("en");

export const universities: Omit<School, "id">[] = [
	{
		name: "Acadia University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Acadia University.png",
	},
	{
		name: "Algoma University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sault Ste. Marie",
		logo: "/university_logos/Algoma University.png",
	},
	{
		name: "Athabasca University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Athabasca University.jpg",
	},
	{
		name: "Bishops University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Bishops University.png",
	},
	{
		name: "Brandon University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Brandon University.jpg",
	},
	{
		name: "Brock University",
		countryCode: "CA",
		regionCode: "ON",
		city: "St. Catharines",
		logo: "/university_logos/Brock University.jpg",
	},
	{
		name: "Campion College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Campion College.jpg",
	},
	{
		name: "Canadian Mennonite University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Canadian Mennonite University.jpg",
	},
	{
		name: "Cape Breton University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Cape Breton University.jpg",
	},
	{
		name: "Capilano University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Capilano University.png",
	},
	{
		name: "Carleton University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Ottawa",
		logo: "/university_logos/Carleton University.jpg",
	},
	{
		name: "Concordia University of Edmonton",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Concordia University of Edmonton.jpg",
	},
	{
		name: "Concordia University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Concordia University.png",
	},
	{
		name: "Dalhousie University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Dalhousie University.jpg",
	},
	{
		name: "Emily Carr University of Art Design",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Emily Carr University of Art  Design.jpg",
	},
	{
		name: "First Nations University of Canada",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/First Nations University of Canada.jpg",
	},
	{
		name: "HEC Montreal",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/HEC Montral.png",
	},
	{
		name: "Huron University College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Huron University College.jpg",
	},
	{
		name: "INRS",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Institut national de la recherche scientifique INRS.png",
	},
	{
		name: "Kings University College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Kings University College.png",
	},
	{
		name: "Kwantlen Polytechnic University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Kwantlen Polytechnic University.png",
	},
	{
		name: "Lakehead University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Thunder Bay",
		logo: "/university_logos/Lakehead University.jpg",
	},
	{
		name: "Laurentian University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sudbury",
		logo: "/university_logos/Laurentian University.png",
	},
	{
		name: "Luther College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Luther College.jpg",
	},
	{
		name: "MacEwan University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/MacEwan University.jpg",
	},
	{
		name: "McGill University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/McGill University.png",
	},
	{
		name: "McMaster University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Hamilton",
		logo: "/university_logos/McMaster University.jpg",
	},
	{
		name: "Memorial University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Memorial University.jpg",
	},
	{
		name: "Mount Allison University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Mount Allison University.png",
	},
	{
		name: "Mount Royal University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Mount Royal University.png",
	},
	{
		name: "Mount Saint Vincent University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Mount Saint Vincent University.png",
	},
	{
		name: "NSCAD University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/NSCAD University.png",
	},
	{
		name: "Nipissing University",
		countryCode: "CA",
		regionCode: "ON",
		city: "North Bay",
		logo: "/university_logos/Nipissing University.png",
	},
	{
		name: "OCAD University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
		logo: "/university_logos/OCAD University.jpg",
	},
	{
		name: "Ontario Tech University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Oshawa",
		logo: "/university_logos/Ontario Tech University.jpg",
	},
	{
		name: "Polytechnique Montreal",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Polytechnique Montral.jpg",
	},
	{
		name: "Queens University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Kingston",
		logo: "/university_logos/Queens University.jpg",
	},
	{
		name: "Redeemer University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Redeemer University.png",
	},
	{
		name: "Royal Military College of Canada",
		countryCode: "CA",
		regionCode: "ON",
		city: "Kingston",
		logo: "/university_logos/Royal Military College of Canada.png",
	},
	{
		name: "Royal Roads University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Royal Roads University.png",
	},
	{
		name: "Saint Marys University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Saint Marys University.jpg",
	},
	{
		name: "Simon Fraser University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Simon Fraser University.jpg",
	},
	{
		name: "St Francis Xavier University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Francis Xavier University.jpg",
	},
	{
		name: "St Jeromes University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Jeromes University.png",
	},
	{
		name: "St Marys University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Marys University.jpg",
	},
	{
		name: "St Pauls College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Pauls College.jpg",
	},
	{
		name: "St Thomas More College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Thomas More College.png",
	},
	{
		name: "St Thomas University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/St Thomas University.jpg",
	},
	{
		name: "The Kings University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/The Kings University.png",
	},
	{
		name: "The University of British Columbia",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/The University of British Columbia.jpg",
	},
	{
		name: "The University of Winnipeg",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/The University of Winnipeg.jpg",
	},
	{
		name: "Thompson Rivers University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Thompson Rivers University.jpg",
	},
	{
		name: "Toronto Metropolitan University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
		logo: "/university_logos/Toronto Metropolitan University.jpg",
	},
	{
		name: "Trent University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Peterborough",
		logo: "/university_logos/Trent University.png",
	},
	{
		name: "Trinity Western University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Trinity Western University.jpg",
	},
	{
		name: "Universite Laval",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit Laval.jpg",
	},
	{
		name: "Universite Sainte-Anne",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit Sainte-Anne.png",
	},
	{
		name: "Universite TLUQ",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit TLUQ.jpg",
	},
	{
		name: "Universite de Moncton",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit de Moncton.jpg",
	},
	{
		name: "Universite de Montreal",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit de Montral.png",
	},
	{
		name: "Universite de Saint-Boniface",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit de Saint-Boniface.png",
	},
	{
		name: "Universite de Sherbrooke",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit de Sherbrooke.jpg",
	},
	{
		name: "Universite de Sudbury",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sudbury",
		logo: "/university_logos/Universit de Sudbury.png",
	},
	{
		name: "Universite du Quebec a Chicoutimi",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec  Chicoutimi UQAC.jpg",
	},
	{
		name: "Universite du Quebec a Montreal",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec  Montral UQAM.jpg",
	},
	{
		name: "Universite du Quebec a Rimouski",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec  Rimouski UQAR.png",
	},
	{
		name: "Universite du Quebec a Trois-Rivieres",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec  Trois-Rivires UQTR.png",
	},
	{
		name: "Universite du Quebec en Abitibi-Temiscamingue",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec en Abitibi-Tmiscamingue UQAT.jpg",
	},
	{
		name: "Universite du Quebec en Outaouais",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec en Outaouais UQO.jpg",
	},
	{
		name: "Universite du Quebec",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Universit du Qubec.jpg",
	},
	{
		name: "University of Alberta",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Alberta.jpg",
	},
	{
		name: "University of Calgary",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Calgary.jpg",
	},
	{
		name: "University of Guelph",
		countryCode: "CA",
		regionCode: "ON",
		city: "Guelph",
		logo: "/university_logos/University of Guelph.png",
	},
	{
		name: "University of Kings College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Kings College.jpg",
	},
	{
		name: "University of Lethbridge",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Lethbridge.jpg",
	},
	{
		name: "University of Manitoba",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Manitoba.jpg",
	},
	{
		name: "University of New Brunswick",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of New Brunswick.jpg",
	},
	{
		name: "University of Northern British Columbia",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Northern British Columbia.png",
	},
	{
		name: "University of Ottawa",
		countryCode: "CA",
		regionCode: "ON",
		city: "Ottawa",
		logo: "/university_logos/University of Ottawa.png",
	},
	{
		name: "University of Prince Edward Island",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Prince Edward Island.jpg",
	},
	{
		name: "University of Regina",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Regina.jpg",
	},
	{
		name: "University of Saskatchewan",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Saskatchewan.png",
	},
	{
		name: "University of St Michaels College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of St Michaels College.jpg",
	},
	{
		name: "University of Toronto",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
		logo: "/university_logos/University of Toronto.png",
	},
	{
		name: "University of Trinity College",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Trinity College.png",
	},
	{
		name: "University of Victoria",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of Victoria.png",
	},
	{
		name: "University of Waterloo",
		countryCode: "CA",
		regionCode: "ON",
		city: "Waterloo",
		logo: "/university_logos/University of Waterloo.png",
	},
	{
		name: "University of Western Ontario",
		countryCode: "CA",
		regionCode: "ON",
		city: "London",
		logo: "/university_logos/Western University.png",
	},
	{
		name: "University of Windsor",
		countryCode: "CA",
		regionCode: "ON",
		city: "Windsor",
		logo: "/university_logos/University of Windsor.png",
	},
	{
		name: "University of the Fraser Valley",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/University of the Fraser Valley.png",
	},
	{
		name: "Vancouver Island University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Vancouver Island University.jpg",
	},
	{
		name: "Victoria University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Victoria University.png",
	},
	{
		name: "Wilfrid Laurier University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Waterloo",
		logo: "/university_logos/Wilfrid Laurier University.jpg",
	},
	{
		name: "York University",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
		logo: "/university_logos/York University.jpg",
	},
	{
		name: "Yukon University",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/Yukon University.png",
	},
	{
		name: "Ecole de technologie superieure ETS",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/cole de technologie suprieure TS.jpg",
	},
	{
		name: "Ecole nationale dadministration publique ENAP",
		countryCode: "CA",
		regionCode: "",
		city: "",
		logo: "/university_logos/cole nationale dadministration publique ENAP.jpg",
	},
];

export const colleges: Omit<School, "id">[] = [
	{
		name: "Algonquin College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Ottawa",
	},
	{ name: "Boréal", countryCode: "CA", regionCode: "ON", city: "Sudbury" },
	{
		name: "Cambrian College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sudbury",
	},
	{
		name: "Canadore College",
		countryCode: "CA",
		regionCode: "ON",
		city: "North Bay",
	},
	{
		name: "Centennial College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
	},
	{
		name: "Conestoga College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Kitchener",
	},
	{
		name: "Confederation College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Thunder Bay",
	},
	{
		name: "Durham College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Oshawa",
	},
	{
		name: "Fanshawe College",
		countryCode: "CA",
		regionCode: "ON",
		city: "London",
	},
	{
		name: "Fleming College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Peterborough",
	},
	{
		name: "George Brown College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
	},
	{
		name: "Georgian College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Barrie",
	},
	{
		name: "Humber College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
	},
	{
		name: "La Cité Collégiale",
		countryCode: "CA",
		regionCode: "ON",
		city: "Ottawa",
	},
	{
		name: "Lambton College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sarnia",
	},
	{
		name: "Loyalist College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Belleville",
	},
	{
		name: "Michener Institute",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
	},
	{
		name: "Mohawk College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Hamilton",
	},
	{
		name: "Niagara College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Welland",
	},
	{
		name: "Niagara Parks School of Horticulture",
		countryCode: "CA",
		regionCode: "ON",
		city: "Niagara Falls",
	},
	{
		name: "Northern College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Timmins",
	},
	{
		name: "Ridgetown Campus",
		countryCode: "CA",
		regionCode: "ON",
		city: "Ridgetown",
	},
	{
		name: "Sault College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Sault Ste. Marie",
	},
	{
		name: "Seneca Polytechnic",
		countryCode: "CA",
		regionCode: "ON",
		city: "Toronto",
	},
	{
		name: "Sheridan College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Oakville",
	},
	{
		name: "St. Clair College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Windsor",
	},
	{
		name: "St. Lawrence College",
		countryCode: "CA",
		regionCode: "ON",
		city: "Kingston",
	},
];

export const schools: Omit<School, "id">[] = [...universities, ...colleges];

export const STRUGGLES = [
	"Anxiety",
	"Depression",
	"Trauma",
	"Suicidal Thoughts",
	"Grief",
	"Academic Burnout",
	"Imposter Syndrome",
	"Procrastination",
	"Perfectionism",
	"Loneliness",
	"Social Anxiety",
	"Relationships",
	"Roommate Conflict",
	"Identity & Belonging",
	"Family Pressure",
	"Discrimination",
	"Sleep Issues",
	"Body Image",
	"Eating Disorder",
	"Chronic Pain",
	"Financial Stress",
	"Substance Use",
	"Other",
];
